volumes:
  eatinerary-data:
    external: true

services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi/app:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_ACCOUNT_API: http://localhost:8070
      REACT_APP_EATERIES_API: http://localhost:8090
      REACT_APP_FOODIES_API: http://localhost:8100
  database:
    image: postgres:14.2-bullseye
    volumes:
      - eatinerary-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=foodies,eateries,owners,users
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432

  foodies-api:
    build:
      context: ./foodies/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8100:8000"
    volumes:
      - ./foodies/api:/app
    depends_on:
      - database
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://foodies:password@database:5432/foodies
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      DJWTO_SIGNING_KEY: 13fcc604df0deed641c6db316ffd027f5bb8120e7ac40a948562e829f0adf5a4

  foodies-poller:
    build:
      context: ./foodies/poll
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./foodies/poll:/app
      - ./foodies/api/foodies_project:/app/foodies_project
      - ./foodies/api/foodies_rest:/app/foodies_rest
    depends_on:
      - database
      - foodies-api
    environment:
      DEBUG: "True"
      EATERIES_API: http://eateries-api:8000
      USERS_API: http://users-api:8000
      DATABASE_URL: postgres://foodies:password@database:5432/foodies
      WAIT_HOSTS: database:5432,foodies-api:8000
      WAIT_TIMEOUT: 240

  eateries-api:
    build:
      context: ./eateries/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8090:8000"
    volumes:
      - ./eateries/api:/app
    depends_on:
      - database
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://eateries:password@database:5432/eateries
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      DJWTO_SIGNING_KEY: 13fcc604df0deed641c6db316ffd027f5bb8120e7ac40a948562e829f0adf5a4

  # Keep these services for future development

  owners-api:
    build:
      context: ./owners/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8000"
    volumes:
      - ./owners/api:/app
    depends_on:
      - database
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://owners:password@database:5432/owners
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      DJWTO_SIGNING_KEY: 13fcc604df0deed641c6db316ffd027f5bb8120e7ac40a948562e829f0adf5a4

  owners-poller:
    build:
      context: ./owners/poll
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./owners/poll:/app
      - ./owners/api/owners_project:/app/owners_project
      - ./owners/api/owners_rest:/app/owners_rest
    depends_on:
      - database
      - owners-api
    environment:
      DEBUG: "True"
      EATERIES_API: http://eateries-api:8000
      USERS_API: http://users-api:8000
      DATABASE_URL: postgres://owners:password@database:5432/owners
      WAIT_HOSTS: database:5432,owners-api:8000
      WAIT_TIMEOUT: 240

  users-api:
    build:
      context: ./users/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8070:8000"
    volumes:
      - ./users/api:/app
    depends_on:
      - database
    environment:
      DEBUG: "True"
      DATABASE_URL: postgres://users:password@database:5432/users
      WAIT_HOSTS: database:5432
      WAIT_TIMEOUT: 240
      DJWTO_SIGNING_KEY: 13fcc604df0deed641c6db316ffd027f5bb8120e7ac40a948562e829f0adf5a4
