# Generated by Django 4.0.3 on 2022-06-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_rest', '0002_alter_eaterylocation_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaterylocation',
            name='country',
            field=models.CharField(default='USA', max_length=200),
        ),
    ]
