# Generated by Django 4.0.3 on 2022-06-11 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("owners_rest", "0002_remove_eateryvo_href"),
    ]

    operations = [
        migrations.AddField(
            model_name="eateryvo",
            name="from_yelp",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="latitude",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="location_address1",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="location_address2",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="location_address3",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="location_city",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="location_country",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="location_state",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="location_zip",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eateryvo",
            name="longitude",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eateryvo",
            name="eatery_name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="EateryTagVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_href", models.CharField(max_length=200)),
                ("tag_name", models.CharField(max_length=40)),
                (
                    "eatery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagsvo",
                        to="owners_rest.eateryvo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EateryOpenHoursVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_href", models.CharField(max_length=200)),
                ("weekday", models.CharField(max_length=200)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "eatery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allopenhoursvo",
                        to="owners_rest.eateryvo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EateryImageVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_href", models.CharField(max_length=200)),
                ("image_url", models.CharField(max_length=200)),
                (
                    "eatery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eateryimagesvo",
                        to="owners_rest.eateryvo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EateryCategoryVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("import_href", models.CharField(max_length=200)),
                ("alias", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                (
                    "eatery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categoriesvo",
                        to="owners_rest.eateryvo",
                    ),
                ),
            ],
        ),
    ]
