# Generated by Django 4.0.3 on 2022-06-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatery',
            name='href',
        ),
    ]
