# Generated by Django 4.0.3 on 2022-06-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0002_remove_eatery_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaterycategory',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='eaterylocation',
            unique_together={('address1', 'address2', 'address3', 'city', 'state', 'zip', 'country')},
        ),
    ]
