# Generated by Django 4.0.3 on 2022-06-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eateries_rest",
            "0003_rename_category_terms_yelpresult_category_term_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eatery",
            name="from_yelp",
            field=models.BooleanField(default=False),
        ),
    ]
