# Generated by Django 4.0.3 on 2022-06-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0003_alter_eaterycategory_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='eatery',
        ),
        migrations.AddField(
            model_name='eatery',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='eateries_rest.tag'),
        ),
    ]
