# Generated by Django 4.0.3 on 2022-06-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0004_remove_tag_eatery_eatery_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatery',
            old_name='tag',
            new_name='tags',
        ),
    ]
