# Generated by Django 4.0.3 on 2022-06-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eateries_rest", "0005_alter_eatery_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eaterylocation",
            old_name="zip",
            new_name="zip_code",
        ),
        migrations.AlterUniqueTogether(
            name="eaterylocation",
            unique_together={
                (
                    "address1",
                    "address2",
                    "address3",
                    "city",
                    "state",
                    "zip_code",
                    "country",
                )
            },
        ),
    ]
