# Generated by Django 4.0.3 on 2022-06-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0005_rename_tag_eatery_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eateryimage',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eatery_images', to='eateries_rest.eatery'),
        ),
        migrations.AlterField(
            model_name='eateryopenhours',
            name='eatery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_hours', to='eateries_rest.eatery'),
        ),
    ]
