# Generated by Django 4.0.3 on 2022-06-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0006_alter_eateryimage_eatery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpSearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YelpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='eateries_rest.yelpsearchterm')),
            ],
        ),
    ]
