# Generated by Django 4.0.3 on 2022-06-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0007_alter_eaterylocation_address2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eaterylocation',
            unique_together=set(),
        ),
    ]
