# Generated by Django 4.0.3 on 2022-06-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eateries_rest", "0008_alter_eaterylocation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="eatery",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="eatery",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="eatery",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
