# Generated by Django 4.0.3 on 2022-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eateries_rest", "0011_alter_eatery_price_alter_eatery_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yelpcategorysearchterm",
            name="category_term",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="yelplocationsearchterm",
            name="location_term",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
