# Generated by Django 4.0.3 on 2022-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eateries_rest', '0017_alter_eaterylocation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eaterycategory',
            name='alias',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
