# Generated by Django 4.0.3 on 2022-06-09 19:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EateryCategoriesVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EateryVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200)),
                ('eatery_name', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200)),
                ('website', models.URLField(unique=True)),
                ('yelp_id', models.CharField(max_length=200, unique=True)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('average_rating', models.FloatField()),
                ('price', models.CharField(max_length=4)),
                ('location_address1', models.CharField(max_length=200)),
                ('location_address2', models.CharField(max_length=200)),
                ('location_address3', models.CharField(max_length=200)),
                ('location_city', models.CharField(max_length=200)),
                ('location_state', models.CharField(max_length=200)),
                ('location_zip', models.CharField(max_length=200)),
                ('location_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Foodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('google_calendar', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkeweredEatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_DateTime', models.DateTimeField(auto_now_add=True)),
                ('updated_DateTime', models.DateTimeField(auto_now=True)),
                ('has_visited', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skewered_eatery', to='foodies_rest.eateryvo')),
                ('foodie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodie', to='foodies_rest.foodie')),
            ],
        ),
        migrations.CreateModel(
            name='EateryTagVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200)),
                ('tag_name', models.CharField(max_length=40)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagsvo', to='foodies_rest.eateryvo')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_DateTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('skewered_restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodies_rest.skeweredeatery')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='foodies_rest.imagevo')),
            ],
        ),
    ]
