# Generated by Django 4.0.3 on 2022-06-09 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EateryCategoriesVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EateryLocationVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('address3', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('country', models.CharField(default='USA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EateryTagVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EateryVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200)),
                ('eatery_name', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=200)),
                ('website', models.URLField(unique=True)),
                ('yelp_id', models.CharField(max_length=200, unique=True)),
                ('review_count', models.PositiveSmallIntegerField(default=0)),
                ('average_rating', models.FloatField()),
                ('price', models.CharField(max_length=4)),
                ('location_address1', models.CharField(max_length=200)),
                ('location_address2', models.CharField(max_length=200)),
                ('location_address3', models.CharField(max_length=200)),
                ('location_city', models.CharField(max_length=200)),
                ('location_state', models.CharField(max_length=200)),
                ('location_zip', models.CharField(max_length=200)),
                ('location_country', models.CharField(max_length=200)),
                ('eatery_open_hours', models.CharField(max_length=200)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodies_categories', to='foodies_rest.eaterycategoriesvo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodies_tag', to='foodies_rest.eaterytagvo')),
            ],
        ),
        migrations.CreateModel(
            name='Foodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('google_calendar', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkeweredEatery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_DateTime', models.DateTimeField(auto_now_add=True)),
                ('updated_DateTime', models.DateTimeField(auto_now=True)),
                ('has_visited', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skewered_eatery', to='foodies_rest.eateryvo')),
                ('foodie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='foodie', to='foodies_rest.foodie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_DateTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('skewered_restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodies_rest.skeweredeatery')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='foodies_rest.imagevo')),
            ],
        ),
    ]
