# Generated by Django 4.0.3 on 2022-06-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eateryvo',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='eateryvo',
            name='eatery_open_hours',
        ),
        migrations.RemoveField(
            model_name='eateryvo',
            name='tag',
        ),
    ]
