# Generated by Django 4.0.3 on 2022-06-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EateryCategoryVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriesvo', to='foodies_rest.eateryvo')),
            ],
        ),
        migrations.CreateModel(
            name='EateryImageVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eateryimagesvo', to='foodies_rest.eateryvo')),
            ],
        ),
        migrations.CreateModel(
            name='EateryOpenHoursVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('eatery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allopenhoursvo', to='foodies_rest.eateryvo')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(unique=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewimages', to='foodies_rest.review')),
            ],
        ),
        migrations.DeleteModel(
            name='EateryCategoriesVO',
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='foodies_rest.reviewimage'),
        ),
        migrations.DeleteModel(
            name='ImageVO',
        ),
    ]
