# Generated by Django 4.0.3 on 2022-06-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodie',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='foodie',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='foodie',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
