# Generated by Django 4.0.3 on 2022-06-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0002_eaterycategoryvo_eateryimagevo_eateryopenhoursvo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eateryopenhoursvo',
            name='weekday',
            field=models.CharField(max_length=200),
        ),
    ]
