# Generated by Django 4.0.3 on 2022-06-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "foodies_rest",
            "0002_rename_eatery_eateryopenhoursvo_eatery_vo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="eaterycategoryvo",
            old_name="eatery",
            new_name="eatery_vo",
        ),
        migrations.RenameField(
            model_name="eateryimagevo",
            old_name="eatery",
            new_name="eatery_vo",
        ),
        migrations.RenameField(
            model_name="eaterytagvo",
            old_name="eatery",
            new_name="eatery_vo",
        ),
    ]
