# Generated by Django 4.0.3 on 2022-06-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0004_alter_eateryimagevo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eateryvo',
            name='from_yelp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
