# Generated by Django 4.0.3 on 2022-06-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0005_eateryvo_from_yelp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
