# Generated by Django 4.0.3 on 2022-06-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0006_remove_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eateryvo',
            name='latitude',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eateryvo',
            name='longitude',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
