# Generated by Django 4.0.3 on 2022-06-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0007_eateryvo_latitude_eateryvo_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eateryvo',
            name='eatery_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eateryvo',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eateryvo',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eateryvo',
            name='website',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eateryvo',
            name='yelp_id',
            field=models.CharField(max_length=200),
        ),
    ]
