# Generated by Django 4.0.3 on 2022-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0008_alter_eateryvo_eatery_name_alter_eateryvo_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eateryvo',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
