# Generated by Django 4.0.3 on 2022-06-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_rest', '0009_foodievo_remove_skeweredeatery_foodie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skeweredeatery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='skeweredeatery',
            unique_together={('eatery_vo', 'foodie_vo')},
        ),
    ]
